### ISSUE TITLE
Provide Kotlin extensions

### ISSUE THREAD

**Issue by turastory** [wirecube/android_additive_animations#13]
```kotlin
AdditiveAnimator.animate(this)
    .addEndAction(object : AnimationEndListener() {
        override fun onAnimationEnd(wasCancelled: Boolean) {
            
        }
    })
```

Function above can be simplified using typealias and lambda.

```kotlin
typealias AnimationEndListener =
    (wasCancelled: Boolean) -> Unit

fun AdditiveAnimator.addEndAction(listener: AnimationEndListener) {
    addEndAction(object : AnimationEndListener() {
        override fun onAnimationEnd(wasCancelled: Boolean) {
            listener(wasCancelled)
        }
    })
}

// Use
AdditiveAnimator.animate(this)
    .addEndAction { wasCancelled ->
         
    }
```

Do you have any plans to do something like this? (Support Kotlin)

**Comment by davidganster** [comment]
Hi,

which version of the library are you using?
The new syntax should already be supported via Java Lambdas since `1.7.1`!
Please let me know if upgrading to this version fixes this issue.

I just realized I didn't make an official release for that because I wanted to tidy something up – I'll fix that today and update the readme/releases for the latest version!

**Comment by turastory** [comment]
Yep, I used version `1.6.2`. When I upgrade to `1.7.2` it fixes the issue.

And thanks for updates - visibility animations are pretty useful!
