### ISSUE TITLE
How to reset, reverse and pause/resume additive animations? 

### ISSUE THREAD

**Issue by StephanSchuster** [wirecube/android_additive_animations#14]
Cool library! Thank you.

One question: How do I reset, reverse and pause/resume additive animations like in [AnimatorSet](https://developer.android.com/reference/android/animation/AnimatorSet)?

**Comment by davidganster** [comment]
Hi Stephan,

thanks, glad you like the library!

These features are unfortunately not supported at the moment due to a conflict with how additive animations and animation chaining work conceptually.

Consider this animation:
```
val animator1 = AdditiveAnimator.animate(view1)
        .alpha(0f)
        .then()
        .alpha(1f)
        .then()
        .target(view2)
        .x(200)
animator1.start()

// wait a little, then make another animation:
AdditiveAnimator.animate(view2).x(100).then().target(view1).alpha(0.5f).start()

// now reset the first one
animator1.reset()
```
What would you expect the alpha value of `view1` to be after the call to 'reset'? What should the `x` value of `view2` be? What would happen to the second running animation on `x` of `view2`, would that also be cancelled? (If not, the view won't arrive at `x = 100`, because that animation assumed that the previous animation would finish – that's why cancelling an animation affects _all_ running animations on a property)
All of these considerations would also have to be made for pausing, resuming and reversing – and I couldn't get a good answer that makes sense in all cases.

That said, implementing pausing/resuming/scrubbing for non-chained animations is rather straight-forward since `AdditiveAnimator` uses a `ValueAnimator` under the hood – I'm just not sure I want to add a feature that is not fully supported in every configuration since that might lead to confusion about correct usage.

Can you give some context as to what you're trying to achieve?
There is usually no need to reset and reverse animations manually, and pausing/resuming can be done by simply cancelling the running animations and making new ones when necessary. 
I understand that the animation curve might not be what you want with this approach, but there might be an easy solution depending on the specific problem you're having.

Cheers,
David
