### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by kazuser** [wirecube/android_additive_animations#21]
Hi there!

Thanks for your lib, it's awesome! What about the same but for iOS? :)

**Comment by davidganster** [comment]
Hi @kazuser, thank you! :) 

Unfortunately, there is no equivalent on iOS when it comes to syntax (since this library leans on the Android `ViewAnimator` patterns). The iOS animation API makes creating a custom animation library much harder (if you want to keep using CoreAnimation), and animations are additive by default since iOS 8, so I saw less need to create an equivalent on iOS.
