### ISSUE TITLE
purpose?

### ISSUE THREAD

**Issue by tenSunFree** [wirecube/android_additive_animations#4]
If it is "return true", when the choice of "Additive animations enabled is false", long press the effect is not ideal
![01](https://user-images.githubusercontent.com/23090085/29202993-cb8765c2-7e9f-11e7-89b4-876e8a79e921.jpg)
Maybe you can change that way, or do you have other ideas?
![02](https://user-images.githubusercontent.com/23090085/29203029-1a787630-7ea0-11e7-9789-288629f447a9.jpg)

**Comment by davidganster** [comment]
Hi,

this is the intended behaviour. 
The demos show what happens when you add lots of animations in both the additive and non-additive way without letting the previous animation finish.
In this case, dragging across the screen will add animations so rapidly that the non-additive version gets stuck completely because the animations get canceled before they have a chance to run.
