### ISSUE TITLE
Cancel repeating animation

### ISSUE THREAD

**Issue by jemshit** [wirecube/android_additive_animations#9]
Hi, how to cancel animation with repeat count INFINITE?
```kotlin
shakeAnimation = AdditiveAnimator.animate(image)
                .setDuration(200L)
                .setInterpolator(LinearInterpolator())

                .rotation(3f)
                .then()
                .rotation(-3f)

                .setRepeatCount(ValueAnimator.INFINITE)
                .setRepeatMode(ValueAnimator.REVERSE)
```

`shakeAnimation.cancelAllAnimations()` does not stop animation.

**Comment by davidganster** [comment]
Hi @jemshit, that should be how you cancel animations...

Can you try doing `AdditiveAnimator.cancelAnimations(image)` to see if that works?

**Comment by jemshit** [comment]
It works, thanks.

**Comment by davidganster** [comment]
Glad you got it to work!

I'll look into why the method you tried didn't cancel the animations, can you post the full animation creation?

**Comment by jemshit** [comment]
Above code is full kotlin code. 'image' is FrameLayout containing
ImageView. I created AdditiveAnimation object and stored in variable. Then
called 'start' and tried to cancel as shown above.

**Comment by davidganster** [comment]
Thanks, I'll try to reproduce. 

Btw, I will probably deprecate and later remove the `cancel()` methods from the animator to discourage storing animator objects.

**Comment by jemshit** [comment]
Ok. What is the reason behind not being able to reuse AdditiveAnimator
objects (start, cancel, then start again)?

**Comment by davidganster** [comment]
Basically it was a design decision to dodge a set of issues that additive animations have - since they are inherently stateful, it's not obvious what should happen in the start - cancel - restart case:
Would the user expect the animation to restart where the view was when the animation was first created? Or should it restart from the current position? 
How would that affect other running additive animations on the same property? What if you `then()`-chain more animations on the same animator after calling `cancel()`?

I didn't (and still don't) have good answers to these questions, and I don't think anything I could come up with would make intuitive sense in all cases.

The current API removes the statefulness by making animators single-use throwaway objects.

**Comment by jemshit** [comment]
I get it 👍
